# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 14:25
from __future__ import unicode_literals

import argent_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argent_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inroom',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argent_app.User'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=argent_app.models.generate_uuid, max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=argent_app.models.generate_uuid, max_length=80, primary_key=True, serialize=False),
        ),
    ]
