# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent_app', '0003_auto_20170803_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host_id',
            new_name='host',
        ),
        migrations.AddField(
            model_name='room',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
